version: 2.1
orbs:
  node: circleci/node@1.1.6

commands:
  add_npmrc:
    steps:
      - run: echo "//npm.pkg.github.com/:_authToken=$GITHUB_AUTH_TOKEN" > ~/.npmrc

  install_dependencies:
    steps:
      - restore_cache:
          keys:
            - dependency-cache-v2-{{ checksum "package-lock.json" }}
      - add_npmrc
      - run: npm install
      - save_cache:
          key: dependency-cache-v2-{{ checksum "package-lock.json" }}
          paths:
              - node_modules

jobs:
  deploy-storybook:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Create GitHub Deployment
                command: sh ./scripts/deployment/start.sh > deployment
            - install_dependencies
            - run: npm run storybook:build
            - store_artifacts:
                path: build-storybook
            - run:
                name: Add GitHub Deployment success status
                command: sh ./scripts/deployment/end.sh success
                when: on_success
            - run:
                name: Add GitHub Deployment error status
                command: sh ./scripts/deployment/end.sh error
                when: on_fail
  lint-and-test:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - node/with-cache:
          steps:
            - install_dependencies
            - run: npm run lint
            # - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - lint-and-test
      - hold:
          type: approval
          requires:
            - lint-and-test
      - deploy-storybook:
          requires:
            - hold


